# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0dd7f8c87694bb421e7749a17d25315f062cff9a633a4c6b10311881c9fc92bf816a4c14c28516b67fcaf5e45bba408c71e30692ce9312a15e96500b6e679cfb

test:
  secret_key_base: 382d719092a35d790b3eaff4203fac5fe741ef1ed6345a96c2837b2880a4ec246669762745b3fefa5c2b6fc6fae724b5662f279988c89233d2b2112b25690890

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
